/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    GieInput: typeof import('@giegie/components')['GieInput']
    GieRichtext: typeof import('@giegie/components')['GieRichtext']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
