/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GieInput: typeof import('@giegie/components')['GieInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  }
}
